name: Publish a container image

on:
  push:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - containerfile: ./Dockerfile
            context: .
            image: local-reranker
            arch: amd64
            runner: ubuntu-24.04
          - containerfile: ./Dockerfile
            context: .
            image: local-reranker
            arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v6
      - name: Set the image metadata
        run: ./scripts/set_image_metadata
      - name: Set lowercase repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"
      - name: Build an image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.image }}-dev
          tags: ${{ env.TAGS }}-${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          context: ${{ matrix.context }}
          containerfiles: |
            ${{ matrix.containerfile }}
          labels: ${{ env.ANNOTATIONS }}

      - name: Push the image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ env.REPO_OWNER_LC }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

  manifest:
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        image:
          - local-reranker

    steps:
      - uses: actions/checkout@v6
      - name: Set the image metadata
        run: ./scripts/set_image_metadata
      - name: Set lowercase repository owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"
      - name: Log in to GHCR
        run: buildah login -u ${{ github.actor }} -p ${{ github.token }} ghcr.io

      - name: Create and push the multi-arch dev manifest
        env:
          REPO: ghcr.io/${{ env.REPO_OWNER_LC }}
          IMAGE: ${{ matrix.image }}-dev
        run: |
          buildah manifest create "${IMAGE}:${TAGS}"
          buildah manifest add "${IMAGE}:${TAGS}" \
            "docker://${REPO}/${IMAGE}:${TAGS}-amd64"
          buildah manifest add "${IMAGE}:${TAGS}" \
            "docker://${REPO}/${IMAGE}:${TAGS}-arm64"
          buildah manifest push --all \
            "${IMAGE}:${TAGS}" \
            "docker://${REPO}/${IMAGE}:${TAGS}"

      - name: Create and push the multi-arch release manifest
        if: (github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'edited'))
        env:
          REPO: ghcr.io/${{ env.REPO_OWNER_LC }}
          DEV_IMAGE: ${{ matrix.image }}-dev
          IMAGE: ${{ matrix.image }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          for dst in latest "${RELEASE_TAG}"; do
            buildah manifest create "${IMAGE}:${dst}"
            buildah manifest add "${IMAGE}:${dst}" \
              "docker://${REPO}/${DEV_IMAGE}:${TAGS}-amd64"
            buildah manifest add "${IMAGE}:${dst}" \
              "docker://${REPO}/${DEV_IMAGE}:${TAGS}-arm64"
            buildah manifest push --all \
              "${IMAGE}:${dst}" \
              "docker://${REPO}/${IMAGE}:${dst}"
          done
